### ISSUE TITLE
DNA genotyping required info for the example data

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/SPEAQeasy-example#2]
Extract just the relevant DNA genotyping information for doing the DNA vs RNA + DNA vs DNA correlation on the 740ish variants for the example samples selected in #1. Note that we'll use only this subset DNA genotyping info + the corresponding RNA for the selected 40 samples for finding and resolving the swaps. That's the ideal scenario. If you are using data from other samples for resolving the swaps, we'll need to discuss this.

**Comment by joshstolz** [comment]
Script was made for subsetting genotype info.
