### ISSUE TITLE
Script for downloading example data

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/SPEAQeasy-example#3]
Write a script that can download the example data. The example DNA genotype data might live in this repo if it's tiny (depends on #2). The FASTQ data should ideally already be publicly available given that in #1 we'll choose data from LIBD public projects. But if it gets complicated, we might need to host the data on AWS (talk to Andrew about this).

The goal is to have a full length example available for `SPEAQeasy` users.

**Comment by lcolladotor** [comment]
Should also include the input phenotype info (prior to resolving the swaps) which will be used as an input in #5

**Comment by joshstolz** [comment]
Script was made for subsetting genotype samples.

**Comment by lcolladotor** [comment]
@joshstolz can you verify whether it's ok to close this issue?

**Comment by lcolladotor** [comment]
@joshstolz @Nick-Eagles can you check this?
