### ISSUE TITLE
Process example data using SPEAQeasy

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/SPEAQeasy-example#4]
We'll want to host the output files from SPEAQeasy from this example, such that others can run the downstream analyses and that we can then point users to the output files in the SPEAQeasy docs. Depending on the size of the files (except the BAM files) we might want to host the output files on GitHub through git-lfs (say 5Gb or less). If it's more, then maybe AWS is the better option. Anyway, version control here the code for processing the data. We can always initially ignore the output files using `.gitignore` before deciding where to host them.

**Comment by Nick-Eagles** [comment]
As an update, the outputs are ready at `/dcl01/lieber/ajaffe/lab/SPEAQeasy-example/pipeline_outputs/` but currently ignored by git. The next step is then determining how to host them as you mentioned.

**Comment by Nick-Eagles** [comment]
We've decided on hosting only the major outputs of interest from this repository, using git LFS where necessary (this is already done).
