### ISSUE TITLE
Code for differential expression analysis and EDA

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/SPEAQeasy-example#6]
Create a directory and Rmd that uses the output of #5 as the input. Then show how to explore the data (PCA), check the ERCCs (Nick can do this part), normalize the data, perform a differential expression analysis using `limma`-voom, find enriched ontologies using `clusterProfiler` and make some heatmaps likely using `pheatmap`. This could be our own LIBD jaffelab guide for differential expression analyses. Feel free to link to Bioconductor workflows and package vignettes as well. You could also use `jaffelab::agePlotter()` for example. Use the same `BiocStyle` and `knitcitations` style as in #5 for the Rmd (with also the output from `sessioninfo::session_info()`).

**Comment by joshstolz** [comment]
I updated a differential expression script to run on the sample files. We may want to look at the model and pca but for now this holds as an example script.

**Comment by lcolladotor** [comment]
Hi @joshstolz, can you verify whether it's ok to close this issue? Thanks!

**Comment by joshstolz** [comment]
Yeah we finished that up.

________________________________
